_wandb:
    value:
        cli_version: 0.23.0
        e:
            ja2xznve2p753csv6m8fjcv8sxxncbrd:
                args:
                    - --config
                    - training/configs/pretrain_h100x4.yaml
                codePath: training/train_h100.py
                codePathLocal: training/train_h100.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "161061273600"
                        used: "9387782144"
                email: jainshouryamaan@gmail.com
                executable: /root/miniconda3/bin/python3.13
                git:
                    commit: 1f1a3f665c575b3b6ed735bf2ce1d11ccbd337b5
                    remote: https://github.com/shouryamaanjain/flow-matching-qwen.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-08100935-59c2-f6c2-a1b2-902926343bfb
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-55553df5-9a8f-07ed-11e1-2832ba6e079b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-af765957-b531-f5d8-a21f-9ec1f7680789
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-7ad3c86b-a21b-a190-18a1-5ebe35da9e63
                host: 6660e76ce786
                memory:
                    total: "2164093689856"
                os: Linux-6.8.0-58-generic-x86_64-with-glibc2.39
                program: /workspace/flow-matching-qwen/training/train_h100.py
                python: CPython 3.13.9
                root: /workspace/flow-matching-qwen
                startedAt: "2025-12-02T18:09:35.914016Z"
                writerId: ja2xznve2p753csv6m8fjcv8sxxncbrd
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.9
            "5": 0.23.0
            "6": 4.57.3
            "12": 0.23.0
            "13": linux-x86_64
global_batch_size:
    value: 128
learning_rate:
    value: 0.0003
max_steps:
    value: 210000
model:
    value: Qwen/Qwen3-1.7B
scheduler_n:
    value: 1
scheduler_type:
    value: polynomial_convex
sequence_length:
    value: 8192
